<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Submenu;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class SubmenuSeeder extends Seeder
{
    public function run()
    {
      Submenu::truncate();

        $now = Carbon::now();
        $submenus = array(

                array('menu_id' => '2','name' => 'Location','sort_id' => '1','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'location','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'Director','sort_id' => '2','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'director','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'Raison D\'etre','sort_id' => '3','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'raison','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'Life at Pinegrove','sort_id' => '4','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'life-at-pinegrove','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'Faculties','sort_id' => '5','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'faculties','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'Group Photo','sort_id' => '6','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'group-photo','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'Scales of Pay','sort_id' => '7','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'scales-of-pay','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'Enrollment','sort_id' => '8','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'enrollment','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'The Board','sort_id' => '9','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'the-board','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'SMC','sort_id' => '10','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'smc','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'Mandatory Disclosure','sort_id' => '11','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'mandatory-disclosure','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'Rules','sort_id' => '12','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'rules','seo_title' => 'Pinegrove School','seo_description' => 'Pinegrove School, established in 1991, is a Co-educational, purely residential, English medium public school affiliated to the Central Board of Secondary Education (CBSE), Delhi','seo_keywords' => 'Pinegrove School, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '3','name' => 'Introduction','sort_id' => '1','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'introduction','seo_title' => NULL,'seo_description' => NULL,'seo_keywords' => NULL,'status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '3','name' => 'Academic Facilities','sort_id' => '2','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'academic-facilities','seo_title' => NULL,'seo_description' => NULL,'seo_keywords' => NULL,'status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '3','name' => 'Games & Sports','sort_id' => '3','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'games-and-sports','seo_title' => NULL,'seo_description' => NULL,'seo_keywords' => NULL,'status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '3','name' => 'Activities','sort_id' => '4','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'activities','seo_title' => NULL,'seo_description' => NULL,'seo_keywords' => NULL,'status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '3','name' => 'Boarding','sort_id' => '5','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'boarding','seo_title' => NULL,'seo_description' => NULL,'seo_keywords' => NULL,'status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '3','name' => 'New Developments','sort_id' => '6','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'new-developments','seo_title' => NULL,'seo_description' => NULL,'seo_keywords' => NULL,'status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '4','name' => 'Admission Process','sort_id' => '1','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'admission-process','seo_title' => 'Admission Process','seo_description' => 'Description of the admission process.','seo_keywords' => 'admission, process, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '4','name' => 'Fees','sort_id' => '2','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'fees','seo_title' => 'Fees','seo_description' => 'Description of the fees.','seo_keywords' => 'fees, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '4','name' => 'Clothing','sort_id' => '3','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'clothing','seo_title' => 'Clothing','seo_description' => 'Description of the clothing requirements.','seo_keywords' => 'clothing, requirements, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '4','name' => 'Withdrawl','sort_id' => '4','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'withdrawl','seo_title' => 'Withdrawl','seo_description' => 'Description of the withdrawl process.','seo_keywords' => 'withdrawl, process, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '4','name' => 'Contact for Admission','sort_id' => '5','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'contact-for-admission','seo_title' => 'Contact for Admission','seo_description' => 'Description of contacting for admission.','seo_keywords' => 'contact, admission, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '4','name' => 'Transfer Certificate','sort_id' => '6','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'transfer-certificate','seo_title' => 'Transfer Certificate','seo_description' => 'Description of the transfer certificate process.','seo_keywords' => 'transfer, certificate, process, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '5','name' => 'Our Founder','sort_id' => '1','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'our-founder','seo_title' => 'Our Founder','seo_description' => 'Description of our founder.','seo_keywords' => 'founder, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '5','name' => 'Alumni','sort_id' => '2','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'alumni','seo_title' => 'Alumni','seo_description' => 'Description of alumni.','seo_keywords' => 'alumni, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '5','name' => 'Guest Book','sort_id' => '3','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'guest-book','seo_title' => 'Guest Book','seo_description' => 'Description of guest book.','seo_keywords' => 'guest book, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '5','name' => 'Grapevine','sort_id' => '4','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'grapevine','seo_title' => 'Grapevine','seo_description' => 'Description of grapevine.','seo_keywords' => 'grapevine, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '5','name' => 'Roll of Honour','sort_id' => '5','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'roll-of-honour','seo_title' => 'Roll of Honour','seo_description' => 'Description of roll of honour.','seo_keywords' => 'roll of honour, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '5','name' => 'Picture Gallery','sort_id' => '6','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'picture-gallery','seo_title' => 'Picture Gallery','seo_description' => 'Description of picture gallery.','seo_keywords' => 'picture gallery, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '6','name' => 'Introduction','sort_id' => '1','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'introduction','seo_title' => 'Introduction','seo_description' => 'Description of introduction.','seo_keywords' => 'introduction, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '6','name' => 'Admission & Fees','sort_id' => '2','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'admission-and-fees','seo_title' => 'Admission & Fees','seo_description' => 'Description of admission & fees.','seo_keywords' => 'admission, fees, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '6','name' => 'Academics','sort_id' => '3','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'academics','seo_title' => 'Academics','seo_description' => 'Description of academics.','seo_keywords' => 'academics, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '6','name' => 'Facilities & Activities','sort_id' => '4','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'facilities-and-activitie','seo_title' => 'Facilities & Activities','seo_description' => 'Description of facilities & activities.','seo_keywords' => 'facilities, activities, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '6','name' => 'Boarding','sort_id' => '5','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'boarding','seo_title' => 'Boarding','seo_description' => 'Description of boarding.','seo_keywords' => 'boarding, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '6','name' => 'Discipline','sort_id' => '6','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'discipline','seo_title' => 'Discipline','seo_description' => 'Description of discipline.','seo_keywords' => 'discipline, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '6','name' => 'Discipline','sort_id' => '6','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_name' => NULL,'slug' => 'discipline','seo_title' => 'Discipline','seo_description' => 'Description of discipline.','seo_keywords' => 'discipline, description','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
        
              
        
        
        );


        foreach ($submenus as &$item) {
          // Get the "name" field value
          $name = $item['name'];
          
          // Generate slug by converting to lowercase and replacing spaces with hyphens
          $slug = str_replace(' ', '-', strtolower($name));
          
          // Store the generated slug in the "slug" field
          $item['slug'] = $slug;
      }
      // Now you can proceed with inserting the updated data into the database
      foreach ($submenus as $submenu) {
          DB::table('submenus')->insert($submenu);
      }
    }
}
